### ISSUE TITLE
"Events" collection has name conflict with Telescope

### ISSUE THREAD

**Issue by yourcelf** [AdmitHub/admithub-common#5]
Telescope uses an `Events` collection to store tracked events (e.g. analytics).  The new [Events](https://github.com/AdmitHub/admithub-common/blob/master/collections/events.js) collection we have refers to college fairs, etc.

Can we rename ours to something less generic, so that this package can coexist with Telescope?  Perhaps "CollegeEvents".

**Comment by AndrewMagliozzi** [comment]
Doh. That's fine. Pete?
